---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ragflow.fullname" . }}-es-config
data:
  node.name: "es01"
  bootstrap.memory_lock: "false"
  discovery.type: "single-node"
  ES_JAVA_OPTS: "-Xms96m -Xmx96m"
  xpack.security.enabled: "true"
  xpack.security.http.ssl.enabled: "false"
  xpack.security.transport.ssl.enabled: "false"
  cluster.routing.allocation.disk.watermark.low: "5gb"
  cluster.routing.allocation.disk.watermark.high: "3gb"
  cluster.routing.allocation.disk.watermark.flood_stage: "2gb"
  TZ: {{ .Values.elasticsearch.timezone | quote }}
  STACK_VERSION: {{ .Values.elasticsearch.stackVersion | quote }}
