apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-es-secrets
type: Opaque
stringData:
  ELASTIC_PASSWORD: {{ .Values.elasticsearch.password | required "elasticsearch.password is required" | quote }}
