apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-minio-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.env.MINIO_ROOT_USER | required "MINIO_ROOT_USER is required" | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.env.MINIO_PASSWORD | required "MINIO_PASSWORD is required" | quote }}
