apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-minio-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.password | required "minio.password is required" | quote }}
