apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-ragflow-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.env.REDIS_PASSWORD | required "REDIS_PASSWORD is required" | quote }}
  MYSQL_PASSWORD: {{ .Values.env.MYSQL_PASSWORD | required "MYSQL_PASSWORD is required" | quote }}
  MINIO_PASSWORD: {{ .Values.env.MINIO_PASSWORD | required "MINIO_PASSWORD is required" | quote }}
  ELASTIC_PASSWORD: {{ .Values.env.ELASTIC_PASSWORD | required "ELASTIC_PASSWORD is required" | quote }}
