apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ragflow.fullname" . }}-redis-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.password | required "redis.password is required" | quote }}